name: code_generator_template
description: A command-line utility to generate Dart code snippets.
version: 1.0.0+1
repository: https://github.com/ysavr/code_generator_template

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  